# Semantic Evaluation - Experiment 05

<h1>Summary<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span><ul class="toc-item"><li><span><a href="#Libraries" data-toc-modified-id="Libraries-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Libraries</a></span></li><li><span><a href="#Definitions" data-toc-modified-id="Definitions-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Definitions</a></span></li></ul></li><li><span><a href="#DataPrep" data-toc-modified-id="DataPrep-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>DataPrep</a></span><ul class="toc-item"><li><span><a href="#Importing-SICK-dataset" data-toc-modified-id="Importing-SICK-dataset-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Importing SICK dataset</a></span><ul class="toc-item"><li><span><a href="#Sampling-N-samples-labeled-as-&quot;contradiction&quot;-for-exploratory-analysis:" data-toc-modified-id="Sampling-N-samples-labeled-as-&quot;contradiction&quot;-for-exploratory-analysis:-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Sampling N samples labeled as "contradiction" for exploratory analysis:</a></span></li></ul></li><li><span><a href="#Importing-&quot;The-Glasgow-Norms&quot;-dataset" data-toc-modified-id="Importing-&quot;The-Glasgow-Norms&quot;-dataset-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Importing "The Glasgow Norms" dataset</a></span><ul class="toc-item"><li><span><a href="#DataPrep:-adjusting-the-column/feature-label" data-toc-modified-id="DataPrep:-adjusting-the-column/feature-label-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>DataPrep: adjusting the column/feature label</a></span></li></ul></li><li><span><a href="#[FAILED]-Tentativa-de-visualizar-no-TensorBoard" data-toc-modified-id="[FAILED]-Tentativa-de-visualizar-no-TensorBoard-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>[FAILED] Tentativa de visualizar no TensorBoard</a></span><ul class="toc-item"><li><span><a href="#Trying-the-same-thing-above,-but-with-fewer-instances:" data-toc-modified-id="Trying-the-same-thing-above,-but-with-fewer-instances:-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Trying the same thing above, but with fewer instances:</a></span></li></ul></li><li><span><a href="#Selecionando-apenas-colunas-com-_M-e-_SD" data-toc-modified-id="Selecionando-apenas-colunas-com-_M-e-_SD-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Selecionando apenas colunas com _M e _SD</a></span></li><li><span><a href="#Buscando-frases-do-dataset-SICK-que-contenham-uma-palavra-específica" data-toc-modified-id="Buscando-frases-do-dataset-SICK-que-contenham-uma-palavra-específica-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Buscando frases do dataset SICK que contenham uma palavra específica</a></span></li><li><span><a href="#Trying-to-visualize-the-features-with-confidence-interval:" data-toc-modified-id="Trying-to-visualize-the-features-with-confidence-interval:-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Trying to visualize the features with confidence interval:</a></span><ul class="toc-item"><li><span><a href="#Finding-an-appropriate-chart-design:" data-toc-modified-id="Finding-an-appropriate-chart-design:-2.6.1"><span class="toc-item-num">2.6.1&nbsp;&nbsp;</span>Finding an appropriate chart design:</a></span></li><li><span><a href="#Creating-a-method-to-visualize-any-word:" data-toc-modified-id="Creating-a-method-to-visualize-any-word:-2.6.2"><span class="toc-item-num">2.6.2&nbsp;&nbsp;</span>Creating a method to visualize any word:</a></span></li></ul></li><li><span><a href="#Experimento-com-Prof.-Heitor" data-toc-modified-id="Experimento-com-Prof.-Heitor-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Experimento com Prof. Heitor</a></span><ul class="toc-item"><li><span><a href="#Definição-das-frases" data-toc-modified-id="Definição-das-frases-2.7.1"><span class="toc-item-num">2.7.1&nbsp;&nbsp;</span>Definição das frases</a></span></li></ul></li><li><span><a href="#Medida-de-proximidade-semântica" data-toc-modified-id="Medida-de-proximidade-semântica-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Medida de proximidade semântica</a></span><ul class="toc-item"><li><span><a href="#Calculando-a-distância-entre-os-vetores:" data-toc-modified-id="Calculando-a-distância-entre-os-vetores:-2.8.1"><span class="toc-item-num">2.8.1&nbsp;&nbsp;</span>Calculando a distância entre os vetores:</a></span></li></ul></li></ul></li><li><span><a href="#Análise-sintática-(POS---Part-Of-Speech)" data-toc-modified-id="Análise-sintática-(POS---Part-Of-Speech)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Análise sintática (POS - Part Of Speech)</a></span></li><li><span><a href="#2022.04.28---Discussão-com-Andrei" data-toc-modified-id="2022.04.28---Discussão-com-Andrei-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2022.04.28 - Discussão com Andrei</a></span><ul class="toc-item"><li><span><a href="#Qual-é-o-problema?" data-toc-modified-id="Qual-é-o-problema?-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Qual é o problema?</a></span><ul class="toc-item"><li><span><a href="#Semantica:" data-toc-modified-id="Semantica:-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Semantica:</a></span></li><li><span><a href="#Objetivo:-questionamentos-do-Andrei" data-toc-modified-id="Objetivo:-questionamentos-do-Andrei-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span><strong>Objetivo:</strong> questionamentos do Andrei</a></span></li></ul></li><li><span><a href="#Segundo-experimento:" data-toc-modified-id="Segundo-experimento:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Segundo experimento:</a></span></li><li><span><a href="#The-cat:" data-toc-modified-id="The-cat:-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>The cat:</a></span></li><li><span><a href="#Man-sweeping" data-toc-modified-id="Man-sweeping-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Man sweeping</a></span></li><li><span><a href="#Man-driving" data-toc-modified-id="Man-driving-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Man driving</a></span></li></ul></li><li><span><a href="#Next-steps" data-toc-modified-id="Next-steps-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Next steps</a></span></li></ul></div>

## Introduction

### Libraries

In [70]:
## Data analysis packages:
import pandas as pd
import numpy as np
from math import isnan  #Verifies if a given value is numerical.

In [72]:
## Visualization packages:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [75]:
## Plotly Express
import plotly.graph_objs as go

In [76]:
import plotly

### Definitions

In [97]:
## Forcing Pandas to display any number of elements
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_seq_items', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_colwidth', None)

In [90]:
## Based on: https://stackoverflow.com/questions/25351968/how-can-i-display-full-non-truncated-dataframe-information-in-html-when-conver
def print_full(x):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 2000)
    pd.set_option('display.float_format', '{:20,.2f}'.format)
    pd.set_option('display.max_colwidth', None)
    print(x)
    pd.reset_option('display.max_rows')
    pd.reset_option('display.max_columns')
    pd.reset_option('display.width')
    pd.reset_option('display.float_format')
    pd.reset_option('display.max_colwidth')

## DataPrep

### Importing SICK dataset
SICK (Sentences Involving Compositional Knowledge) data set, from University of Trento and available at http://clic.cimec.unitn.it/composes/sick/, "consists of 10,000 English sentence pairs, built starting from two existing paraphrase sets: the [8K ImageFlickr data set](http://nlp.cs.illinois.edu/HockenmaierGroup/data.html) and the [SEMEVAL-2012 Semantic Textual Similarity Video Descriptions data set](http://www.cs.york.ac.uk/semeval-2012/task6/index.php?id=data). Each sentence pair is annotated for relatedness in meaning and for the entailment relation between the two elements."

Fields description:
- pair_ID: sentence pair ID

- sentence_A: sentence A

- sentence_B: sentence B

- entailment_label: textual entailment gold label (NEUTRAL, ENTAILMENT, or CONTRADICTION)

- relatedness_score: semantic relatedness gold score (on a 1-5 continuous scale)

- entailment_AB: entailment for the A-B order (A_neutral_B, A_entails_B, or A_contradicts_B)

- entailment_BA: entailment for the B-A order (B_neutral_A, B_entails_A, or B_contradicts_A)

- sentence_A_original: original sentence from which sentence A is derived

- sentence_B_original: original sentence from which sentence B is derived

- sentence_A_dataset: dataset from which the original sentence A was extracted (FLICKR vs. SEMEVAL)

- sentence_B_dataset: dataset from which the original sentence B was extracted (FLICKR vs. SEMEVAL)

- SemEval_set: set including the sentence pair in SemEval 2014 Task 1 (TRIAL, TRAIN, or TEST)

In [81]:
## Reading the dataset file:
data_sick = pd.read_table('../data/dataset_SICK/SICK/SICK.txt')

In [82]:
## Gathering general information from the dataset (it is already prepared for analysis)
data_sick.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9840 entries, 0 to 9839
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pair_ID              9840 non-null   int64
 1   sentence_A           9840 non-null   object
 2   sentence_B           9840 non-null   object
 3   entailment_label     9840 non-null   object
 4   relatedness_score    9840 non-null   float64
 5   entailment_AB        9840 non-null   object
 6   entailment_BA        9840 non-null   object
 7   sentence_A_original  9840 non-null   object
 8   sentence_B_original  9840 non-null   object
 9   sentence_A_dataset   9840 non-null   object
 10  sentence_B_dataset   9840 non-null   object
 11  SemEval_set          9840 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 922.6+ KB

In [83]:
## Grouping by entailment label:
data_sick.groupby(['entailment_label'])['pair_ID'].agg('count').reset_index()

  entailment_label  pair_ID
0    CONTRADICTION     1424
1       ENTAILMENT     2821
2          NEUTRAL     5595

----
#### Sampling N samples labeled as "contradiction" for exploratory analysis:
*A random state is set to allow reproducibility.*

In [84]:
## Defining the number of samples:
N_sick = 5
## Choosing arbitrarily a random state:
random_state = 98

In [85]:
## Sampling the SICK data labeled as "contradiction":
sample_sick = data_sick[data_sick['entailment_label'] == 'CONTRADICTION'].sample(n=N_sick, 
                                                                                 random_state=random_state)

In [92]:
print_full(sample_sick)

      pair_ID                                                                              sentence_A                                                                               sentence_B entailment_label    relatedness_score    entailment_AB    entailment_BA                                             sentence_A_original                                             sentence_B_original sentence_A_dataset sentence_B_dataset SemEval_set
591       592  A woman is taking off a cloak, which is very large, and revealing an extravagant dress  A woman is putting on a cloak, which is very large, and concealing an extravagant dress    CONTRADICTION                 3.50  A_contradicts_B  B_contradicts_A  A woman taking off a large cloak revealing a extravagant dress  A woman taking off a large cloak revealing a extravagant dress             FLICKR             FLICKR       TRIAL
9483     9643                                      A brown and white dog is running through the river                                   A brown and white dog is not running through the river    CONTRADICTION                 3.60  A_contradicts_B  B_contradicts_A              a brown and white dog is running through the river              a brown and white dog is running through the river             FLICKR             FLICKR       TRAIN
4797     4921                                                        There is no man playing a guitar                                                    A man is singing and playing a guitar    CONTRADICTION                 4.10  A_contradicts_B  B_contradicts_A                           a man is singing and playing a guitar                                       a man is playing a guitar            SEMEVAL            SEMEVAL       TRAIN
1569     1590                                       The chef is carefully drying the oil from the pan                                        The chef is carefully pouring some oil into a pan    CONTRADICTION                 3.50  A_contradicts_B  B_contradicts_A                                  The chef pours oil in the pan.                                  The chef pours oil in the pan.            SEMEVAL            SEMEVAL        TEST
4739     4861                                                                    A man is not dancing                                                                         A man is dancing    CONTRADICTION                 3.80  A_contradicts_B  B_contradicts_A                                                a man is dancing                                                a man is dancing            SEMEVAL            SEMEVAL        TEST

-----
### Buscando frases do dataset SICK que contenham uma palavra específica

In [101]:
data_sick[data_sick['sentence_A'].str.contains(' love', case=False)]

      pair_ID                                         sentence_A                                  sentence_B entailment_label  relatedness_score entailment_AB entailment_BA            sentence_A_original                     sentence_B_original sentence_A_dataset sentence_B_dataset SemEval_set
1733     1754  A flute is being played in a lovely way by a girl           A flute is being played by a girl       ENTAILMENT                4.6   A_entails_B   B_neutral_A     A girl is playing a flute.              A girl is playing a flute.            SEMEVAL            SEMEVAL       TRIAL
1740     1761  A flute is being played in a lovely way by a girl                One woman is playing a flute       ENTAILMENT                3.7   A_entails_B   B_neutral_A  A woman is playing the flute.              A girl is playing a flute.            SEMEVAL            SEMEVAL        TEST
1872     1893       The guitar player loves the man passionately  A person is singing and playing the guitar          NEUTRAL                2.6   A_neutral_B   B_neutral_A     A man is playing a guitar.  A man is playing a guitar and singing.            SEMEVAL            SEMEVAL        TEST

----
#### Definição das frases

In [66]:
data_sick.loc[1733]

pair_ID                                                             1754
sentence_A             A flute is being played in a lovely way by a girl
sentence_B                             A flute is being played by a girl
entailment_label                                              ENTAILMENT
relatedness_score                                                    4.6
entailment_AB                                                A_entails_B
entailment_BA                                                B_neutral_A
sentence_A_original                           A girl is playing a flute.
sentence_B_original                           A girl is playing a flute.
sentence_A_dataset                                               SEMEVAL
sentence_B_dataset                                               SEMEVAL
SemEval_set                                                        TRIAL
Name: 1733, dtype: object

### Medida de proximidade semântica

Frases similares:  
1. The **dog** is **ugly**.  
2. That **dog** is **awful** and **horrible**.  

Frases diferentes:  

3. The **snake** is **dangerous**.  
4. **Love** is **beautiful**.

Tarefa:
- Pegar as 8 dimensões médias para cada uma das palavras destacadas.
- Fazer a média dessas medidas.

> Frase 1: "the dog is ugly"

In [74]:
## Recuperando as 8 dimensões das palavras da frase:
df_frase1 = dataset.loc[['dog','ugly']]
df_frase1

       AROU_M  VAL_M  DOM_M  CNC_M  IMAG_M  FAM_M  AOA_M  SIZE_M
words
dog     6.147  7.067  6.242  6.833   6.889  6.840  1.735   3.273
ugly    4.147  2.000  3.606  2.939   5.177  6.303  2.677   4.382

In [75]:
## Calculando a média das palavras que compõem a frase:
vetor_frase1 = df_frase1.describe().loc['mean']
vetor_frase1 = np.array(vetor_frase1).T.tolist()
vetor_frase1

[5.147,
 4.5335,
 4.9239999999999995,
 4.886,
 6.0329999999999995,
 6.5715,
 2.206,
 3.8274999999999997]

> A mesma operação para a frase "that dog is awful and horrible".

In [76]:
## Recuperando as 8 dimensões das palavras da frase:
df_frase2 = dataset.loc[['dog','awful','horrible']]
df_frase2

          AROU_M  VAL_M  DOM_M  CNC_M  IMAG_M  FAM_M  AOA_M  SIZE_M
words
dog        6.147  7.067  6.242  6.833   6.889  6.840  1.735   3.273
awful      3.000  2.118  3.971  2.206   3.000  5.882  3.657   4.429
horrible   4.742  1.688  3.807  2.531   2.719  5.923  2.938   5.100

In [77]:
## Calculando a média das palavras que compõem a frase:
vetor_frase2 = df_frase2.describe().loc['mean']
vetor_frase2 = np.array(vetor_frase2).T.tolist()
vetor_frase2

[4.629666666666666,
 3.624333333333334,
 4.673333333333334,
 3.856666666666667,
 4.2026666666666666,
 6.215,
 2.776666666666667,
 4.267333333333333]

> Frase 3: "the snake is dangerous."

In [78]:
## Recuperando as 8 dimensões das palavras da frase:
df_frase3 = dataset.loc[['snake','dangerous']]
df_frase3

           AROU_M  VAL_M  DOM_M  CNC_M  IMAG_M  FAM_M  AOA_M  SIZE_M
words
snake       4.909  3.657  5.257  6.714   6.657  5.647  2.529   3.091
dangerous   7.353  2.677  4.563  3.114   4.594  5.879  3.057   5.824

In [79]:
## Calculando a média das palavras que compõem a frase:
vetor_frase3 = df_frase3.describe().loc['mean']
vetor_frase3 = np.array(vetor_frase3).T.tolist()
vetor_frase3

[6.131, 3.167, 4.91, 4.914, 5.625500000000001, 5.763, 2.793, 4.4575]

> Frase 4: "love is beautiful."

In [80]:
## Recuperando as 8 dimensões das palavras da frase:
df_frase4 = dataset.loc[['love','beautiful']]
df_frase4

           AROU_M  VAL_M  DOM_M  CNC_M  IMAG_M  FAM_M  AOA_M  SIZE_M
words
love        8.147  8.647  5.303  2.849   4.471  6.906  1.912   6.294
beautiful   7.029  8.441  6.344  2.515   5.412  6.517  2.559   5.333

In [81]:
## Calculando a média das palavras que compõem a frase:
vetor_frase4 = df_frase4.describe().loc['mean']
vetor_frase4 = np.array(vetor_frase4).T.tolist()
vetor_frase4

[7.588,
 8.544,
 5.8235,
 2.6820000000000004,
 4.9415,
 6.7115,
 2.2355,
 5.8134999999999994]

#### Calculando a distância entre os vetores:

In [86]:
from scipy.spatial import distance

In [87]:
## Dist v1 e v2
distance.euclidean(vetor_frase1, vetor_frase2)

2.4925699310372638

In [88]:
## Dist v1 e v3
distance.euclidean(vetor_frase1, vetor_frase3)

2.0970826760049306

In [89]:
## Dist v2 e v3
distance.euclidean(vetor_frase2, vetor_frase3)

2.4294668711011025

In [90]:
## Dist v4 e v3
distance.euclidean(vetor_frase4, vetor_frase3)

6.3536080104142405

In [91]:
## Dist v4 e v2
distance.euclidean(vetor_frase4, vetor_frase2)

6.25567430640197

## Análise sintática (POS - Part Of Speech)
Com base no tutorial disposto em https://neptune.ai/blog/exploratory-data-analysis-natural-language-processing-tools.  

Parts of speech (POS) tagging is a method that assigns part of speech labels to words in a sentence. There are eight main parts of speech:

- Noun (NN)- Joseph, London, table, cat, teacher, pen, city
- Verb (VB)- read, speak, run, eat, play, live, walk, have, like, are, is
- Adjective(JJ)- beautiful, happy, sad, young, fun, three
- Adverb(RB)- slowly, quietly, very, always, never, too, well, tomorrow
- Preposition (IN)- at, on, in, from, with, near, between, about, under
- Conjunction (CC)- and, or, but, because, so, yet, unless, since, if
- Pronoun(PRP)- I, you, we, they, he, she, it, me, us, them, him, her, this
- Interjection (INT)- Ouch! Wow! Great! Help! Oh! Hey! Hi!

In [1]:
phrase = 'Love is something beautiful.'

Also using Spacy library: https://spacy.io/

In [2]:
#!pip install -U spacy

Collecting spacy
  Downloading spacy-3.7.2-cp311-cp311-win_amd64.whl.metadata (26 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.10-cp311-cp311-win_amd64.whl.metadata (2.0 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.8-cp311-cp311-win_amd64.whl.metadata (8.6 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.9-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
Collecting thinc<8.3.0,>=8.1.8 (from spacy)
  Downloading thinc-8.2.2-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.2-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.4.8-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.4.0,>=0.1.0 (from spacy)
  Downloading weasel-0.3.4-py3-none-any.whl.metadata (4.7 kB)
Collecting typer<0.10.0,>=0.3.0 (from spacy)
  Downloading typer-0.9.0-py3-none-any.whl (45 kB)
     ---------------------------------------- 0.0/45.9 kB ? eta -:--:--
     ---------------------------------------- 45.9/45.9 kB ? eta 0:00:00
Collecting smart-open<7.0.0,>=5.2.1 (from spacy)
  Downloading smart_open-6.4.0-py3-none-any.whl.metadata (21 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Downloading pydantic-2.5.3-py3-none-any.whl.metadata (65 kB)
     ---------------------------------------- 0.0/65.6 kB ? eta -:--:--
     ---------------------------------------- 65.6/65.6 kB ? eta 0:00:00
Collecting jinja2 (from spacy)
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: setuptools in c:\users\tiago\onedrive - univali\phd\atividades de pesquisa\semantic_similarity\.venv\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\tiago\onedrive - univali\phd\atividades de pesquisa\semantic_similarity\.venv\lib\site-packages (from spacy) (23.2)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Downloading langcodes-3.3.0-py3-none-any.whl (181 kB)
     ---------------------------------------- 0.0/181.6 kB ? eta -:--:--
     ------------------------------------- 181.6/181.6 kB 10.7 MB/s eta 0:00:00
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-1.26.3-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.6 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading pydantic_core-2.14.6-cp311-none-win_amd64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.6.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.1.8->spacy)
  Downloading blis-0.7.11-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.1.8->spacy)
  Downloading confection-0.1.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in c:\users\tiago\onedrive - univali\phd\atividades de pesquisa\semantic_similarity\.venv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting click<9.0.0,>=7.1.1 (from typer<0.10.0,>=0.3.0->spacy)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cloudpathlib<0.17.0,>=0.7.0 (from weasel<0.4.0,>=0.1.0->spacy)
  Downloading cloudpathlib-0.16.0-py3-none-any.whl.metadata (14 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy)
  Downloading MarkupSafe-2.1.4-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Downloading spacy-3.7.2-cp311-cp311-win_amd64.whl (12.1 MB)
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
   ------ --------------------------------- 1.9/12.1 MB 41.2 MB/s eta 0:00:01
   --------------------- ------------------ 6.5/12.1 MB 69.5 MB/s eta 0:00:01
   ---------------------------------------  11.8/12.1 MB 110.0 MB/s eta 0:00:01
   ---------------------------------------- 12.1/12.1 MB 93.8 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.8-cp311-cp311-win_amd64.whl (39 kB)
Downloading murmurhash-1.0.10-cp311-cp311-win_amd64.whl (25 kB)
Using cached numpy-1.26.3-cp311-cp311-win_amd64.whl (15.8 MB)
Downloading preshed-3.0.9-cp311-cp311-win_amd64.whl (122 kB)
   ---------------------------------------- 0.0/122.3 kB ? eta -:--:--
   ---------------------------------------- 122.3/122.3 kB ? eta 0:00:00
Downloading pydantic-2.5.3-py3-none-any.whl (381 kB)
   ---------------------------------------- 0.0/381.9 kB ? eta -:--:--
   --------------------------------------- 381.9/381.9 kB 24.8 MB/s eta 0:00:00
Downloading pydantic_core-2.14.6-cp311-none-win_amd64.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ---------------------- ----------------- 1.0/1.9 MB 64.6 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.9 MB 64.6 MB/s eta 0:00:01
   ---------------------------------------  1.9/1.9 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 13.3 MB/s eta 0:00:00
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading smart_open-6.4.0-py3-none-any.whl (57 kB)
   ---------------------------------------- 0.0/57.0 kB ? eta -:--:--
   ---------------------------------------- 57.0/57.0 kB ? eta 0:00:00
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.4.8-cp311-cp311-win_amd64.whl (479 kB)
   ---------------------------------------- 0.0/479.7 kB ? eta -:--:--
   ---------------------------------------- 479.7/479.7 kB ? eta 0:00:00
Downloading thinc-8.2.2-cp311-cp311-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 91.9 MB/s eta 0:00:00
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Downloading wasabi-1.1.2-py3-none-any.whl (27 kB)
Downloading weasel-0.3.4-py3-none-any.whl (50 kB)
   ---------------------------------------- 0.0/50.1 kB ? eta -:--:--
   ---------------------------------------- 50.1/50.1 kB ? eta 0:00:00
Using cached Jinja2-3.1.3-py3-none-any.whl (133 kB)
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading blis-0.7.11-cp311-cp311-win_amd64.whl (6.6 MB)
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   --------------------- ------------------ 3.6/6.6 MB 111.4 MB/s eta 0:00:01
   ---------------------------------------- 6.6/6.6 MB 84.5 MB/s eta 0:00:00
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ---------------------------------------- 0.0/97.9 kB ? eta -:--:--
   ---------------------------------------- 97.9/97.9 kB ? eta 0:00:00
Downloading cloudpathlib-0.16.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.0 kB ? eta -:--:--
   ---------------------------------------- 45.0/45.0 kB 2.2 MB/s eta 0:00:00
Downloading confection-0.1.4-py3-none-any.whl (35 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Downloading MarkupSafe-2.1.4-cp311-cp311-win_amd64.whl (17 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: cymem, wasabi, urllib3, typing-extensions, tqdm, spacy-loggers, spacy-legacy, smart-open, numpy, murmurhash, MarkupSafe, langcodes, idna, cloudpathlib, click, charset-normalizer, certifi, catalogue, annotated-types, typer, srsly, requests, pydantic-core, preshed, jinja2, blis, pydantic, confection, weasel, thinc, spacy
Successfully installed MarkupSafe-2.1.4 annotated-types-0.6.0 blis-0.7.11 catalogue-2.0.10 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 cloudpathlib-0.16.0 confection-0.1.4 cymem-2.0.8 idna-3.6 jinja2-3.1.3 langcodes-3.3.0 murmurhash-1.0.10 numpy-1.26.3 preshed-3.0.9 pydantic-2.5.3 pydantic-core-2.14.6 requests-2.31.0 smart-open-6.4.0 spacy-3.7.2 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.4.8 thinc-8.2.2 tqdm-4.66.1 typer-0.9.0 typing-extensions-4.9.0 urllib3-2.1.0 wasabi-1.1.2 weasel-0.3.4

In [3]:
#!python -m spacy download en_core_web_sm
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl (587.7 MB)
     ---------------------------------------- 0.0/587.7 MB ? eta -:--:--
     -------------------------------------- 0.0/587.7 MB 682.7 kB/s eta 0:14:21
     ---------------------------------------- 0.1/587.7 MB 1.2 MB/s eta 0:08:18
     ---------------------------------------- 0.6/587.7 MB 4.8 MB/s eta 0:02:02
     ---------------------------------------- 1.2/587.7 MB 7.2 MB/s eta 0:01:22
     ---------------------------------------- 2.0/587.7 MB 9.3 MB/s eta 0:01:04
     --------------------------------------- 3.0/587.7 MB 11.4 MB/s eta 0:00:52
     --------------------------------------- 4.3/587.7 MB 13.7 MB/s eta 0:00:43
     --------------------------------------- 5.9/587.7 MB 16.3 MB/s eta 0:00:36
      -------------------------------------- 7.8/587.7 MB 19.3 MB/s eta 0:00:31
      ------------------------------------- 10.3/587.7 MB 27.3 MB/s eta 0:00:22
      ------------------------------------- 12.3/587.7 MB 38.5 MB/s eta 0:00:15
     - ------------------------------------ 16.1/587.7 MB 54.7 MB/s eta 0:00:11
     - ------------------------------------ 20.7/587.7 MB 73.1 MB/s eta 0:00:08
     - ------------------------------------ 25.2/587.7 MB 93.9 MB/s eta 0:00:06
     - ------------------------------------ 25.5/587.7 MB 65.6 MB/s eta 0:00:09
     - ------------------------------------ 29.4/587.7 MB 73.1 MB/s eta 0:00:08
     - ------------------------------------ 29.4/587.7 MB 73.1 MB/s eta 0:00:08
     -- ----------------------------------- 32.6/587.7 MB 46.7 MB/s eta 0:00:12
     -- ----------------------------------- 33.6/587.7 MB 43.7 MB/s eta 0:00:13
     -- ----------------------------------- 34.2/587.7 MB 34.6 MB/s eta 0:00:17
     -- ----------------------------------- 37.9/587.7 MB 40.9 MB/s eta 0:00:14
     -- ----------------------------------- 37.9/587.7 MB 40.9 MB/s eta 0:00:14
     -- ----------------------------------- 40.8/587.7 MB 40.9 MB/s eta 0:00:14
     -- ----------------------------------- 42.1/587.7 MB 38.5 MB/s eta 0:00:15
     -- ----------------------------------- 42.6/587.7 MB 31.2 MB/s eta 0:00:18
     -- ----------------------------------- 46.3/587.7 MB 40.9 MB/s eta 0:00:14
     -- ----------------------------------- 46.3/587.7 MB 40.9 MB/s eta 0:00:14
     --- ---------------------------------- 49.9/587.7 MB 40.9 MB/s eta 0:00:14
     --- ---------------------------------- 50.5/587.7 MB 40.9 MB/s eta 0:00:14
     --- ---------------------------------- 51.4/587.7 MB 31.2 MB/s eta 0:00:18
     --- ---------------------------------- 54.7/587.7 MB 40.9 MB/s eta 0:00:14
     --- ---------------------------------- 54.7/587.7 MB 40.9 MB/s eta 0:00:14
     --- ---------------------------------- 58.3/587.7 MB 40.9 MB/s eta 0:00:13
     --- ---------------------------------- 58.9/587.7 MB 40.9 MB/s eta 0:00:13
     --- ---------------------------------- 60.2/587.7 MB 31.1 MB/s eta 0:00:17
     ---- --------------------------------- 63.1/587.7 MB 43.7 MB/s eta 0:00:12
     ---- --------------------------------- 63.1/587.7 MB 43.7 MB/s eta 0:00:12
     ---- --------------------------------- 66.1/587.7 MB 38.6 MB/s eta 0:00:14
     ---- --------------------------------- 67.3/587.7 MB 40.9 MB/s eta 0:00:13
     ---- --------------------------------- 69.3/587.7 MB 40.9 MB/s eta 0:00:13
     ---- --------------------------------- 71.5/587.7 MB 40.9 MB/s eta 0:00:13
     ---- --------------------------------- 71.5/587.7 MB 40.9 MB/s eta 0:00:13
     ---- --------------------------------- 75.7/587.7 MB 40.9 MB/s eta 0:00:13
     ---- --------------------------------- 75.7/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 78.1/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 79.9/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 80.0/587.7 MB 31.2 MB/s eta 0:00:17
     ----- -------------------------------- 84.1/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 84.1/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 86.5/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 88.4/587.7 MB 40.9 MB/s eta 0:00:13
     ----- -------------------------------- 88.6/587.7 MB 31.2 MB/s eta 0:00:17
     ----- -------------------------------- 92.6/587.7 MB 43.5 MB/s eta 0:00:12
     ----- -------------------------------- 92.6/587.7 MB 43.5 MB/s eta 0:00:12
     ------ ------------------------------- 94.5/587.7 MB 40.9 MB/s eta 0:00:13
     ------ ------------------------------- 96.8/587.7 MB 38.6 MB/s eta 0:00:13
     ------ ------------------------------- 97.2/587.7 MB 31.2 MB/s eta 0:00:16
     ------ ------------------------------ 101.0/587.7 MB 40.9 MB/s eta 0:00:12
     ------ ------------------------------ 101.0/587.7 MB 40.9 MB/s eta 0:00:12
     ------ ------------------------------ 104.3/587.7 MB 43.7 MB/s eta 0:00:12
     ------ ------------------------------ 105.2/587.7 MB 43.7 MB/s eta 0:00:12
     ------ ------------------------------ 106.0/587.7 MB 32.8 MB/s eta 0:00:15
     ------ ------------------------------ 109.4/587.7 MB 38.5 MB/s eta 0:00:13
     ------ ------------------------------ 109.4/587.7 MB 38.5 MB/s eta 0:00:13
     ------- ----------------------------- 113.0/587.7 MB 40.9 MB/s eta 0:00:12
     ------- ----------------------------- 113.6/587.7 MB 40.9 MB/s eta 0:00:12
     ------- ----------------------------- 114.9/587.7 MB 31.1 MB/s eta 0:00:16
     ------- ----------------------------- 117.8/587.7 MB 43.5 MB/s eta 0:00:11
     ------- ----------------------------- 117.8/587.7 MB 43.5 MB/s eta 0:00:11
     ------- ----------------------------- 121.2/587.7 MB 40.9 MB/s eta 0:00:12
     ------- ----------------------------- 122.0/587.7 MB 38.5 MB/s eta 0:00:13
     ------- ----------------------------- 123.7/587.7 MB 31.2 MB/s eta 0:00:15
     ------- ----------------------------- 126.2/587.7 MB 40.9 MB/s eta 0:00:12
     ------- ----------------------------- 126.3/587.7 MB 32.7 MB/s eta 0:00:15
     -------- ---------------------------- 130.5/587.7 MB 43.5 MB/s eta 0:00:11
     -------- ---------------------------- 130.5/587.7 MB 43.5 MB/s eta 0:00:11
     -------- ---------------------------- 130.6/587.7 MB 32.7 MB/s eta 0:00:14
     -------- ---------------------------- 134.7/587.7 MB 43.7 MB/s eta 0:00:11
     -------- ---------------------------- 134.7/587.7 MB 43.7 MB/s eta 0:00:11
     -------- ---------------------------- 138.9/587.7 MB 40.9 MB/s eta 0:00:11
     -------- ---------------------------- 138.9/587.7 MB 40.9 MB/s eta 0:00:11
     -------- ---------------------------- 141.6/587.7 MB 46.7 MB/s eta 0:00:10
     --------- --------------------------- 143.1/587.7 MB 43.7 MB/s eta 0:00:11
     --------- --------------------------- 143.1/587.7 MB 32.8 MB/s eta 0:00:14
     --------- --------------------------- 147.3/587.7 MB 40.9 MB/s eta 0:00:11
     --------- --------------------------- 147.3/587.7 MB 40.9 MB/s eta 0:00:11
     --------- --------------------------- 149.7/587.7 MB 40.9 MB/s eta 0:00:11
     --------- --------------------------- 151.5/587.7 MB 40.9 MB/s eta 0:00:11
     --------- --------------------------- 152.0/587.7 MB 31.2 MB/s eta 0:00:14
     --------- --------------------------- 155.7/587.7 MB 40.9 MB/s eta 0:00:11
     --------- --------------------------- 155.7/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 159.2/587.7 MB 43.7 MB/s eta 0:00:10
     ---------- -------------------------- 160.0/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 161.0/587.7 MB 32.8 MB/s eta 0:00:14
     ---------- -------------------------- 164.2/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 164.2/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 167.8/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 168.4/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 169.9/587.7 MB 32.7 MB/s eta 0:00:13
     ---------- -------------------------- 172.6/587.7 MB 40.9 MB/s eta 0:00:11
     ---------- -------------------------- 172.6/587.7 MB 40.9 MB/s eta 0:00:11
     ----------- ------------------------- 176.9/587.7 MB 43.7 MB/s eta 0:00:10
     ----------- ------------------------- 176.9/587.7 MB 43.7 MB/s eta 0:00:10
     ----------- ------------------------- 178.6/587.7 MB 32.7 MB/s eta 0:00:13
     ----------- ------------------------- 181.1/587.7 MB 40.9 MB/s eta 0:00:10
     ----------- ------------------------- 181.1/587.7 MB 32.7 MB/s eta 0:00:13
     ----------- ------------------------- 185.3/587.7 MB 40.9 MB/s eta 0:00:10
     ----------- ------------------------- 185.3/587.7 MB 40.9 MB/s eta 0:00:10
     ----------- ------------------------- 187.3/587.7 MB 40.9 MB/s eta 0:00:10
     ----------- ------------------------- 189.5/587.7 MB 40.9 MB/s eta 0:00:10
     ----------- ------------------------- 189.6/587.7 MB 32.8 MB/s eta 0:00:13
     ------------ ------------------------ 193.8/587.7 MB 40.9 MB/s eta 0:00:10
     ------------ ------------------------ 193.8/587.7 MB 40.9 MB/s eta 0:00:10
     ------------ ------------------------ 196.0/587.7 MB 43.5 MB/s eta 0:00:09
     ------------ ------------------------ 198.0/587.7 MB 43.7 MB/s eta 0:00:09
     ------------ ------------------------ 198.1/587.7 MB 32.8 MB/s eta 0:00:12
     ------------ ------------------------ 202.2/587.7 MB 40.9 MB/s eta 0:00:10
     ------------ ------------------------ 202.2/587.7 MB 40.9 MB/s eta 0:00:10
     ------------ ------------------------ 205.0/587.7 MB 43.7 MB/s eta 0:00:09
     ------------ ------------------------ 206.4/587.7 MB 40.9 MB/s eta 0:00:10
     ------------- ----------------------- 206.8/587.7 MB 32.7 MB/s eta 0:00:12
     ------------- ----------------------- 210.7/587.7 MB 43.7 MB/s eta 0:00:09
     ------------- ----------------------- 210.7/587.7 MB 43.7 MB/s eta 0:00:09
     ------------- ----------------------- 213.8/587.7 MB 40.9 MB/s eta 0:00:10
     ------------- ----------------------- 214.9/587.7 MB 40.9 MB/s eta 0:00:10
     ------------- ----------------------- 215.6/587.7 MB 32.8 MB/s eta 0:00:12
     ------------- ----------------------- 219.1/587.7 MB 40.9 MB/s eta 0:00:10
     ------------- ----------------------- 219.2/587.7 MB 32.7 MB/s eta 0:00:12
     -------------- ---------------------- 222.9/587.7 MB 40.9 MB/s eta 0:00:09
     -------------- ---------------------- 223.4/587.7 MB 43.5 MB/s eta 0:00:09
     -------------- ---------------------- 224.4/587.7 MB 31.1 MB/s eta 0:00:12
     -------------- ---------------------- 227.6/587.7 MB 40.9 MB/s eta 0:00:09
     -------------- ---------------------- 227.6/587.7 MB 40.9 MB/s eta 0:00:09
     -------------- ---------------------- 230.8/587.7 MB 40.9 MB/s eta 0:00:09
     -------------- ---------------------- 231.9/587.7 MB 40.9 MB/s eta 0:00:09
     -------------- ---------------------- 233.4/587.7 MB 31.2 MB/s eta 0:00:12
     -------------- ---------------------- 236.1/587.7 MB 40.9 MB/s eta 0:00:09
     -------------- ---------------------- 236.1/587.7 MB 32.7 MB/s eta 0:00:11
     --------------- --------------------- 239.9/587.7 MB 43.5 MB/s eta 0:00:08
     --------------- --------------------- 240.3/587.7 MB 40.9 MB/s eta 0:00:09
     --------------- --------------------- 242.2/587.7 MB 40.9 MB/s eta 0:00:09
     --------------- --------------------- 244.6/587.7 MB 40.9 MB/s eta 0:00:09
     --------------- --------------------- 244.6/587.7 MB 32.8 MB/s eta 0:00:11
     --------------- --------------------- 248.8/587.7 MB 43.7 MB/s eta 0:00:08
     --------------- --------------------- 248.8/587.7 MB 43.7 MB/s eta 0:00:08
     --------------- --------------------- 251.6/587.7 MB 43.5 MB/s eta 0:00:08
     --------------- --------------------- 253.0/587.7 MB 43.7 MB/s eta 0:00:08
     --------------- --------------------- 253.5/587.7 MB 32.8 MB/s eta 0:00:11
     ---------------- -------------------- 257.3/587.7 MB 40.9 MB/s eta 0:00:09
     ---------------- -------------------- 257.3/587.7 MB 40.9 MB/s eta 0:00:09
     ---------------- -------------------- 260.5/587.7 MB 43.7 MB/s eta 0:00:08
     ---------------- -------------------- 261.5/587.7 MB 40.9 MB/s eta 0:00:08
     ---------------- -------------------- 262.3/587.7 MB 31.2 MB/s eta 0:00:11
     ---------------- -------------------- 265.7/587.7 MB 43.7 MB/s eta 0:00:08
     ---------------- -------------------- 265.8/587.7 MB 34.4 MB/s eta 0:00:10
     ---------------- -------------------- 269.4/587.7 MB 40.9 MB/s eta 0:00:08
     ---------------- -------------------- 270.0/587.7 MB 40.9 MB/s eta 0:00:08
     ----------------- ------------------- 271.3/587.7 MB 32.8 MB/s eta 0:00:10
     ----------------- ------------------- 274.2/587.7 MB 40.9 MB/s eta 0:00:08
     ----------------- ------------------- 274.2/587.7 MB 32.7 MB/s eta 0:00:10
     ----------------- ------------------- 278.5/587.7 MB 40.9 MB/s eta 0:00:08
     ----------------- ------------------- 278.5/587.7 MB 40.9 MB/s eta 0:00:08
     ----------------- ------------------- 280.4/587.7 MB 40.9 MB/s eta 0:00:08
     ----------------- ------------------- 282.7/587.7 MB 40.9 MB/s eta 0:00:08
     ----------------- ------------------- 282.7/587.7 MB 32.8 MB/s eta 0:00:10
     ------------------ ------------------ 286.9/587.7 MB 43.7 MB/s eta 0:00:07
     ------------------ ------------------ 286.9/587.7 MB 43.7 MB/s eta 0:00:07
     ------------------ ------------------ 288.8/587.7 MB 40.9 MB/s eta 0:00:08
     ------------------ ------------------ 291.2/587.7 MB 40.9 MB/s eta 0:00:08
     ------------------ ------------------ 291.2/587.7 MB 32.7 MB/s eta 0:00:10
     ------------------ ------------------ 295.4/587.7 MB 40.9 MB/s eta 0:00:08
     ------------------ ------------------ 295.4/587.7 MB 40.9 MB/s eta 0:00:08
     ------------------ ------------------ 297.4/587.7 MB 40.9 MB/s eta 0:00:08
     ------------------ ------------------ 299.6/587.7 MB 40.9 MB/s eta 0:00:08
     ------------------ ------------------ 299.7/587.7 MB 32.8 MB/s eta 0:00:09
     ------------------- ----------------- 303.8/587.7 MB 40.9 MB/s eta 0:00:07
     ------------------- ----------------- 303.9/587.7 MB 38.5 MB/s eta 0:00:08
     ------------------- ----------------- 306.3/587.7 MB 43.5 MB/s eta 0:00:07
     ------------------- ----------------- 308.1/587.7 MB 43.7 MB/s eta 0:00:07
     ------------------- ----------------- 308.2/587.7 MB 32.8 MB/s eta 0:00:09
     ------------------- ----------------- 312.4/587.7 MB 40.9 MB/s eta 0:00:07
     ------------------- ----------------- 312.4/587.7 MB 40.9 MB/s eta 0:00:07
     ------------------- ----------------- 315.1/587.7 MB 43.7 MB/s eta 0:00:07
     ------------------- ----------------- 316.6/587.7 MB 40.9 MB/s eta 0:00:07
     ------------------- ----------------- 316.9/587.7 MB 32.7 MB/s eta 0:00:09
     -------------------- ---------------- 320.8/587.7 MB 40.9 MB/s eta 0:00:07
     -------------------- ---------------- 320.8/587.7 MB 40.9 MB/s eta 0:00:07
     -------------------- ---------------- 322.8/587.7 MB 40.9 MB/s eta 0:00:07
     -------------------- ---------------- 325.1/587.7 MB 38.5 MB/s eta 0:00:07
     -------------------- ---------------- 325.5/587.7 MB 31.2 MB/s eta 0:00:09
     -------------------- ---------------- 329.3/587.7 MB 43.7 MB/s eta 0:00:06
     -------------------- ---------------- 329.4/587.7 MB 34.4 MB/s eta 0:00:08
     -------------------- ---------------- 332.7/587.7 MB 40.9 MB/s eta 0:00:07
     --------------------- --------------- 333.6/587.7 MB 43.7 MB/s eta 0:00:06
     --------------------- --------------- 334.5/587.7 MB 32.7 MB/s eta 0:00:08
     --------------------- --------------- 337.9/587.7 MB 40.9 MB/s eta 0:00:07
     --------------------- --------------- 337.9/587.7 MB 32.8 MB/s eta 0:00:08
     --------------------- --------------- 341.9/587.7 MB 43.7 MB/s eta 0:00:06
     --------------------- --------------- 342.1/587.7 MB 40.9 MB/s eta 0:00:07
     --------------------- --------------- 343.6/587.7 MB 32.7 MB/s eta 0:00:08
     --------------------- --------------- 346.4/587.7 MB 40.9 MB/s eta 0:00:06
     --------------------- --------------- 346.4/587.7 MB 32.7 MB/s eta 0:00:08
     ---------------------- -------------- 350.0/587.7 MB 40.9 MB/s eta 0:00:06
     ---------------------- -------------- 350.6/587.7 MB 40.9 MB/s eta 0:00:06
     ---------------------- -------------- 351.9/587.7 MB 31.2 MB/s eta 0:00:08
     ---------------------- -------------- 354.9/587.7 MB 40.9 MB/s eta 0:00:06
     ---------------------- -------------- 354.9/587.7 MB 34.6 MB/s eta 0:00:07
     ---------------------- -------------- 358.6/587.7 MB 40.9 MB/s eta 0:00:06
     ---------------------- -------------- 359.1/587.7 MB 43.7 MB/s eta 0:00:06
     ---------------------- -------------- 360.6/587.7 MB 31.2 MB/s eta 0:00:08
     ---------------------- -------------- 363.3/587.7 MB 40.9 MB/s eta 0:00:06
     ---------------------- -------------- 363.4/587.7 MB 32.8 MB/s eta 0:00:07
     ----------------------- ------------- 367.5/587.7 MB 40.9 MB/s eta 0:00:06
     ----------------------- ------------- 367.5/587.7 MB 40.9 MB/s eta 0:00:06
     ----------------------- ------------- 369.6/587.7 MB 40.9 MB/s eta 0:00:06
     ----------------------- ------------- 371.8/587.7 MB 43.5 MB/s eta 0:00:05
     ----------------------- ------------- 372.0/587.7 MB 32.7 MB/s eta 0:00:07
     ----------------------- ------------- 376.0/587.7 MB 40.9 MB/s eta 0:00:06
     ----------------------- ------------- 376.1/587.7 MB 34.4 MB/s eta 0:00:07
     ----------------------- ------------- 378.7/587.7 MB 43.7 MB/s eta 0:00:05
     ----------------------- ------------- 380.2/587.7 MB 40.9 MB/s eta 0:00:06
     ----------------------- ------------- 380.5/587.7 MB 32.8 MB/s eta 0:00:07
     ------------------------ ------------ 384.4/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------ ------------ 384.6/587.7 MB 34.4 MB/s eta 0:00:06
     ------------------------ ------------ 387.3/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------ ------------ 388.6/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------ ------------ 389.2/587.7 MB 31.1 MB/s eta 0:00:07
     ------------------------ ------------ 392.9/587.7 MB 43.5 MB/s eta 0:00:05
     ------------------------ ------------ 393.1/587.7 MB 34.4 MB/s eta 0:00:06
     ------------------------ ------------ 396.5/587.7 MB 43.7 MB/s eta 0:00:05
     ------------------------- ----------- 397.1/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------- ----------- 398.2/587.7 MB 32.7 MB/s eta 0:00:06
     ------------------------- ----------- 401.4/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------- ----------- 401.7/587.7 MB 32.7 MB/s eta 0:00:06
     ------------------------- ----------- 405.4/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------- ----------- 405.6/587.7 MB 43.5 MB/s eta 0:00:05
     ------------------------- ----------- 406.9/587.7 MB 31.2 MB/s eta 0:00:06
     ------------------------- ----------- 409.9/587.7 MB 40.9 MB/s eta 0:00:05
     ------------------------- ----------- 410.2/587.7 MB 32.8 MB/s eta 0:00:06
     -------------------------- ---------- 413.9/587.7 MB 40.9 MB/s eta 0:00:05
     -------------------------- ---------- 414.1/587.7 MB 40.9 MB/s eta 0:00:05
     -------------------------- ---------- 415.6/587.7 MB 31.2 MB/s eta 0:00:06
     -------------------------- ---------- 418.3/587.7 MB 40.9 MB/s eta 0:00:05
     -------------------------- ---------- 418.8/587.7 MB 32.8 MB/s eta 0:00:06
     -------------------------- ---------- 422.6/587.7 MB 40.9 MB/s eta 0:00:05
     -------------------------- ---------- 422.6/587.7 MB 40.9 MB/s eta 0:00:05

In [4]:
import spacy

In [5]:
# Load English tokenizer, tagger, parser and NER
nlp = spacy.load("en_core_web_lg")

In [6]:
phrase = "The cat is on the table"

In [7]:
doc = nlp(phrase)

In [8]:
spacy.displacy.render(doc, style='dep', jupyter=True, options={'distance':90})

-----

In [12]:
import nltk
from nltk import word_tokenize

In [13]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\tiago\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\tiago\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [14]:
tokens=word_tokenize(phrase)
nltk.pos_tag(tokens)

[('The', 'DT'),
 ('cat', 'NN'),
 ('is', 'VBZ'),
 ('on', 'IN'),
 ('the', 'DT'),
 ('table', 'NN')]

## 2022.04.28 - Discussão com Andrei

### Qual é o problema? 
- Queremos medir a similaridade de duas coisas.
- Se a métrica utilizada, o valor for o mesmo, podemos presumir que o significado pode ser semelhante.  

#### Semantica:
- Objetiva: sintática (Spacy)
- Subjetiva: ... psicometria. (como foi determinado o ACF??)

#### **Objetivo:** questionamentos do Andrei

- Conseguimos avaliar os atributos (ACF) de uma sentença??
    - Supondo que consigo avaliá-los, o que é possível extrair deles? 
    - É relevante?? Qual é a interpretabilidade da métrica? 
        - Por que essa sentença é mais próxima da outra?

- Ou conseguimos extrair features das frases a partir dos atributos (ACF)?

### Segundo experimento:
Faltou no The Glasgow Norm alguma palavra ou verbo... Como a gente conseguiria contornar essa situação? 

1. Utilizar um word embedding para achar o termo mais próximo àquele que não foi encontrado e aí utilizar por referência...  

2. (Com a premissa de que funcionaria o word embedding) Seria possível expandir o "Glasgow Norm" para um número maior de termos?

https://colab.research.google.com/github/bentrevett/pytorch-sentiment-analysis/blob/master/B%20-%20A%20Closer%20Look%20at%20Word%20Embeddings.ipynb  

word_vector = get_vector(glove, 'india')

closest_words(glove, word_vector)

### The cat:

- A cat is chasing a dog
- A cat chases a dog
- A cat is chasing around a german shepherd dog more than twice its size
- A cat is scaring away a dog
- A cat chases a large dog around the yard
- ERRADA: A dog is chasing a cat
- CERTA: A cat is running after a dog

In [15]:
p1 = 'a cat is chasing a dog'
p2 = 'A dog is chasing a cat'
p3 = 'A cat is running after a dog'

In [16]:
doc = nlp(p1)
spacy.displacy.render(doc, style='dep', jupyter=True, options={'distance':90})

In [17]:
doc = nlp(p3)
spacy.displacy.render(doc, style='dep', jupyter=True, options={'distance':90})

-> Substituir "cat" por "kant"...

### Man sweeping

REFERENCIAS

A man sweeps the floor of a gym  
A man sweeps the gymnasium floor with a dust broom  
A man in a blue shirt and black trousers sweeping a gym floor  
A man in a blue shirt is sweeping a classroom  
A man in black pants is mopping the floor of a gym room  

ERRADO: A man in a blue shirt and black pants is working out in a gym
CERTO: A person is mopping the gym floor

### Man driving

A man is driving a car  
A man driving a car

A person walks with thick boots through the rough ways  
There is someone advertising some boots  
A man is walking in the forest area  
A person walks wearing a black trecking shore and climbed a snow mountain  
Person is showing his new boots and their advantages  
A pair of gray hiking boots are shown as the narrator states boots are the most important part of hiking  
A guy is using boots to hike in the snow  

ERRADA: A pair of gray hiking boots is showing the forest area
CERTA: A pair of hiking boots are shown and then a man walks along the snowy forest

### Trying SpaCy similarity modules:

In [18]:
doc1 = nlp("I like salty fries and hamburgers.")
doc2 = nlp("Fast food tastes very good.")

In [19]:
# Similarity of two documents
print(doc1, "<->", doc2, doc1.similarity(doc2))

I like salty fries and hamburgers. <-> Fast food tastes very good. 0.6871286202797843

In [20]:
# Similarity of tokens and spans
french_fries = doc1[2:4]
burgers = doc1[5]
print(french_fries, "<->", burgers, french_fries.similarity(burgers))

salty fries <-> hamburgers 0.6901010870933533

In [37]:
nlp('I never loved this song!').similarity(nlp('I loved this music!'))

0.9504706708543073

### Trying the Sense2Vec lib:
It can be added to the SpaCy pipeline:
https://github.com/explosion/sense2vec

In [39]:
from sense2vec import Sense2VecComponent

In [40]:
s2v = nlp.add_pipe('sense2vec')

In [44]:
#s2v = s2v.from_disk('../data/s2v_reddit_2015_md.tar.gz')

### Trying Martino Mensio "Universal Sentence Encoder"

In [47]:
import spacy_universal_sentence_encoder

WARNING:tensorflow:From c:\Users\tiago\OneDrive - UNIVALI\PhD\atividades de pesquisa\semantic_similarity\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [48]:
nlp = spacy_universal_sentence_encoder.load_model('en_use_md')

WARNING:tensorflow:From c:\Users\tiago\OneDrive - UNIVALI\PhD\atividades de pesquisa\semantic_similarity\.venv\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From c:\Users\tiago\OneDrive - UNIVALI\PhD\atividades de pesquisa\semantic_similarity\.venv\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

Downloaded https://tfhub.dev/google/universal-sentence-encoder/4, Total size: 987.47MB

WARNING:tensorflow:From c:\Users\tiago\OneDrive - UNIVALI\PhD\atividades de pesquisa\semantic_similarity\.venv\Lib\site-packages\tensorflow_hub\module_v2.py:126: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

WARNING:tensorflow:From c:\Users\tiago\OneDrive - UNIVALI\PhD\atividades de pesquisa\semantic_similarity\.venv\Lib\site-packages\tensorflow_hub\module_v2.py:126: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

In [49]:
# your sentences
search_doc = nlp("This was very strange argument between american and british person")

main_doc = nlp("He was from Japan, but a true English gentleman in my eyes, and another one of the reasons as to why I liked going to school.")

print(main_doc.similarity(search_doc))
# this will print 0.310783598221594

0.31078365503069183

In [65]:
phrase1 = nlp('I love this music.')
phrase2 = nlp('This music is great!')

print(phrase1.similarity(phrase2))

0.8758808481438215

Compare with this result: https://medium.com/@tanner.overcash/semantic-similarity-calculations-using-nlp-and-python-a-soft-introduction-1f31df965e40

In [55]:
phrase1 = nlp('rivers woods and hills')
phrase2 = nlp('streams forests and mountains')

print(phrase1.similarity(phrase2))

0.6043704096375386

In [67]:
nlp('I hear this music!').similarity(nlp('I sing this music!'))

0.6563543163308533